# le fichier de configuraion gitlab-ci.yml pour lancer la Framework Autotester2

image: docker:latest  

services:
  - docker:dind

stages:
  - evaluate   # Definir notre stage ou job evaluate pour le pipeline 

before_script:
  # copy the source code of project Autoteter2 from root to current directory
  - cp -R ../../../src src
  - cp ../../../feat3p feat3p
  - cp -R src src_copy

variables:
  PYTHONPATH: $PYTHONPATH:$(pwd)/src_copy/scenarios/tools:$(pwd)/src_copy/utils/:$(pwd)/src_copy/isolate/

evaluate:
  # utiliser image docker contenant les dependances nécessaires et le code source de notre projet
  image : registry.gitlab.com/projet-long/autotester2/autotester2-image:latest  
  stage: evaluate
  script:
    - export PYTHONPATH=$PYTHONPATH:./src_copy/utils
    - export PYTHONPATH=$PYTHONPATH:./src_copy/utils:./src_copy/scenarios/results
    - export PYTHONPATH=$PYTHONPATH:./src_copy/isolate
    - export PYTHONPATH=$PYTHONPATH:./src_copy/main
    # lancer le main script sh du pipeline 
    - sh src/main/main_pipeline.sh
